### ISSUE TITLE
ボタンがインクの上にくるときがある

### ISSUE THREAD

**Issue by sesta** [Battloika/NawabariNet#28]
githubのsshボタンなど

**Comment by suiyujin** [comment]
![uploads/5bd37a51-6c0d-4ff9-b634-fc1a5da90ca8/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5bd37a51-6c0d-4ff9-b634-fc1a5da90ca8%2Fblob)
